package com.crazy.taolove.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.crazy.taolove.entity.ExpressionGroup;
import com.crazy.taolove.entity.Contact;
import com.crazy.taolove.entity.Dynamic;
import com.crazy.taolove.entity.Conversation;
import com.crazy.taolove.entity.NameList;
import com.crazy.taolove.entity.IMessage;
import com.crazy.taolove.entity.Gold;
import com.crazy.taolove.entity.Expression;

import com.crazy.taolove.greendao.ExpressionGroupDao;
import com.crazy.taolove.greendao.ContactDao;
import com.crazy.taolove.greendao.DynamicDao;
import com.crazy.taolove.greendao.ConversationDao;
import com.crazy.taolove.greendao.NameListDao;
import com.crazy.taolove.greendao.IMessageDao;
import com.crazy.taolove.greendao.GoldDao;
import com.crazy.taolove.greendao.ExpressionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig expressionGroupDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig dynamicDaoConfig;
    private final DaoConfig conversationDaoConfig;
    private final DaoConfig nameListDaoConfig;
    private final DaoConfig iMessageDaoConfig;
    private final DaoConfig goldDaoConfig;
    private final DaoConfig expressionDaoConfig;

    private final ExpressionGroupDao expressionGroupDao;
    private final ContactDao contactDao;
    private final DynamicDao dynamicDao;
    private final ConversationDao conversationDao;
    private final NameListDao nameListDao;
    private final IMessageDao iMessageDao;
    private final GoldDao goldDao;
    private final ExpressionDao expressionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        expressionGroupDaoConfig = daoConfigMap.get(ExpressionGroupDao.class).clone();
        expressionGroupDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        dynamicDaoConfig = daoConfigMap.get(DynamicDao.class).clone();
        dynamicDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        nameListDaoConfig = daoConfigMap.get(NameListDao.class).clone();
        nameListDaoConfig.initIdentityScope(type);

        iMessageDaoConfig = daoConfigMap.get(IMessageDao.class).clone();
        iMessageDaoConfig.initIdentityScope(type);

        goldDaoConfig = daoConfigMap.get(GoldDao.class).clone();
        goldDaoConfig.initIdentityScope(type);

        expressionDaoConfig = daoConfigMap.get(ExpressionDao.class).clone();
        expressionDaoConfig.initIdentityScope(type);

        expressionGroupDao = new ExpressionGroupDao(expressionGroupDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        dynamicDao = new DynamicDao(dynamicDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);
        nameListDao = new NameListDao(nameListDaoConfig, this);
        iMessageDao = new IMessageDao(iMessageDaoConfig, this);
        goldDao = new GoldDao(goldDaoConfig, this);
        expressionDao = new ExpressionDao(expressionDaoConfig, this);

        registerDao(ExpressionGroup.class, expressionGroupDao);
        registerDao(Contact.class, contactDao);
        registerDao(Dynamic.class, dynamicDao);
        registerDao(Conversation.class, conversationDao);
        registerDao(NameList.class, nameListDao);
        registerDao(IMessage.class, iMessageDao);
        registerDao(Gold.class, goldDao);
        registerDao(Expression.class, expressionDao);
    }
    
    public void clear() {
        expressionGroupDaoConfig.clearIdentityScope();
        contactDaoConfig.clearIdentityScope();
        dynamicDaoConfig.clearIdentityScope();
        conversationDaoConfig.clearIdentityScope();
        nameListDaoConfig.clearIdentityScope();
        iMessageDaoConfig.clearIdentityScope();
        goldDaoConfig.clearIdentityScope();
        expressionDaoConfig.clearIdentityScope();
    }

    public ExpressionGroupDao getExpressionGroupDao() {
        return expressionGroupDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public DynamicDao getDynamicDao() {
        return dynamicDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public NameListDao getNameListDao() {
        return nameListDao;
    }

    public IMessageDao getIMessageDao() {
        return iMessageDao;
    }

    public GoldDao getGoldDao() {
        return goldDao;
    }

    public ExpressionDao getExpressionDao() {
        return expressionDao;
    }

}
